import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import './globals.css'
import { Inter, Fira_Code } from "next/font/google";
import { ui } from '@clerk/ui'
import { esES  } from '@clerk/localizations'

const mainFont = Inter({
	variable: "--font-main",
	subsets: ["latin"],
});

const monoFont = Fira_Code({
	variable: "--font-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: 'Clerk Next.js Quickstart',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="es">
			<body className={`${mainFont.variable} ${monoFont.variable} antialiased`}>
				<ClerkProvider
					signInUrl="/sign-in"
					signUpUrl="/sign-up"
					ui={ui}
					localization={esES }
				>
					{children}
				</ClerkProvider>
			</body>
		</html>
	)
}